server:
  port: 8080
  context-path: /pengwx
message:
  subscribeMsg: "欢迎关注少鹏哥的公众号!\n\n请按照以下要求操作：\n回复\"1\"，获取作者简介。\n回复\"2\"，获取公司简介。\n输入\"?\"，呼出此菜单。"
  selfInfo: "作者姓名：向少鹏\n籍贯：湖北，武汉\n爱好：编程、健身、唱歌"
  companyInfo: "企鹅医生（北京腾康汇医科技有限公司）是由腾讯、基汇资本、医联、红杉资本中国基金联合组建，由腾讯控股的互联网+实体医疗并线发展的数字健康服务企业。企鹅医生专注为个人和家庭提供优质、安全的全流程健康管理服务。"